# Generated by Django 5.0.1 on 2024-01-12 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_banners/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(2097152, message='File size cannot exceed 2 MB.'), django.core.validators.MinValueValidator(1280, message='Width must be at least 1280 pixels.'), django.core.validators.MinValueValidator(720, message='Height must be at least 720 pixels.')]),
        ),
    ]
