# Generated by Django 5.0.1 on 2024-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='confirm_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
